version: '2'
services:
    jhipstersampleapplication2-app:
        image: jhipstersampleapplication2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipstersampleapplication2-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterSampleApplication2
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://jhipstersampleapplication2-elasticsearch:9200
        ports:
            - 8080:8080
    jhipstersampleapplication2-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstersampleapplication2-mongodb
    jhipstersampleapplication2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstersampleapplication2-elasticsearch
